### ISSUE TITLE
It does not work on iOS

### ISSUE THREAD

**Issue by AurelianTimu** [juicycleff/flutter-unity-view-widget#156]
Hi,

After following precisely the documentation, the example project does not work on iOS no matter what I do.

I am getting the same error that a lot of people have reported already:
`'UnityFramework/UnityFramework.h' file not found`

What is the issue? How can this be fixed?
While I do appreciate the amount of work put into this, also the fact that this is an open source effort, I must say it is disappointing to see that not even the example project works.

**Comment by byferdi42** [comment]
what happened here worked for me

[](https://github.com/Unity-Technologies/uaal-example/blob/master/docs/ios.md)

**Comment by byferdi42** [comment]
what happened here worked for me

`https://github.com/Unity-Technologies/uaal-example/blob/master/docs/ios.md`

**Comment by skypu3** [comment]
Because unity build is based on arm64, so you need to do those on flutter_unity_widget:
1. Architecture should be arm64.
2. Build Active Architecture Only to Yes. 

<img width="905" alt="截圖 2020-06-12 下午4 44 02" src="https://user-images.githubusercontent.com/70039/84483501-fcedc180-accb-11ea-9396-eba81008f943.png">

**Comment by maxbhoria** [comment]
hi anyone have solved this because I am not able to solve using above settings. I am using my simulator device using flutter 12 and ios min 10 and ios max 13.5.

**Comment by maxbhoria** [comment]
> Hi,
> 
> After following precisely the documentation, the example project does not work on iOS no matter what I do.
> 
> I am getting the same error that a lot of people have reported already:
> `'UnityFramework/UnityFramework.h' file not found`
> 
> What is the issue? How can this be fixed?
> While I do appreciate the amount of work put into this, also the fact that this is an open source effort, I must say it is disappointing to see that not even the example project works.

Have resolved this? If yes please guide me how to solve.

**Comment by MugOfPaul** [comment]
@maxbhoria Unity will not build or run in the iOS Simulator so I would guess that is your issue.

**Comment by dangkhoa0303** [comment]
@maxbhoria I ran into the same issue. Then, I tried to set up exactly like what the Demo app was set up. What I did was to copy the Editor, Plugins, and JsonDotNet folders, link.xml file, and UnityMessageManager.cs [from the Demo app](https://github.com/snowballdigital/flutter-unity-view-widget/tree/master/example/unity/DemoApp/Assets) to Assets/ folder. Then, I exported to iOS again.

The issue was resolved after I've done that. However, I ran into another issue when the app just closed right away whenever it navigated to a screen that had the UnityWidget :(

**Comment by Soorya611** [comment]
> @maxbhoria I ran into the same issue. Then, I tried to set up exactly like what the Demo app was set up. What I did was to copy the Editor, Plugins, and JsonDotNet folders, link.xml file, and UnityMessageManager.cs [from the Demo app](https://github.com/snowballdigital/flutter-unity-view-widget/tree/master/example/unity/DemoApp/Assets) to Assets/ folder. Then, I exported to iOS again.
> 
> The issue was resolved after I've done that. However, I ran into another issue when the app just closed right away whenever it navigated to a screen that had the UnityWidget. I think the problem happened because I was using AR Foundation Unity. It worked normally on Android, but it didn't work on iOS.

hey, did you found a fix/solution for this?

**Comment by dangkhoa0303** [comment]
@Soorya611 Check this out and it will solve the problem: https://github.com/snowballdigital/flutter-unity-view-widget/issues/132#issuecomment-618892588

**Comment by Ahmadre** [comment]
> Because unity build is based on arm64, so you need to do those on flutter_unity_widget:
> 
> 1. Architecture should be arm64.
> 2. Build Active Architecture Only to Yes.
> 
> <img alt="截圖 2020-06-12 下午4 44 02" width="905" src="https://user-images.githubusercontent.com/70039/84483501-fcedc180-accb-11ea-9396-eba81008f943.png">

How are you coming to that screen in XCode???

**Comment by juicycleff** [comment]
please use the new build script and instructions :)
