### ISSUE TITLE
Unable to Build IOS project

### ISSUE THREAD

**Issue by patryk191129** [juicycleff/flutter-unity-view-widget#220]
Hello,

I've got problems with building iOS version of the app. I tried using the newest version of the plugin and older versions (2.0.0, 2.0.0+1 2.0.0+2) but the same error persists.
`In file included from /Users/devmac/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-2.0.0+2/ios/Classes/FlutterUnityView.m:9:
    In file included from /Users/devmac/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-2.0.0+2/ios/Classes/FlutterUnityView.h:11:
    /Users/devmac/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-2.0.0+2/ios/Classes/UnityUtils.h:2:10: fatal error: 'UnityFramework/UnityFramework.h' file not found
    #include <UnityFramework/UnityFramework.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
`

I'm Using Unity 2019.4.15f1 and flutter 1.22. Here's my report of flutter doctor:

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G73, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)
`

Also android build works fine without any issues.

**Comment by juicycleff** [comment]
@patryk191129 please follow the docs in the readme to setup iOS

**Comment by WouterVandenputte** [comment]
I followed the documentation to the letter and I also encounter the issue. You could perhaps give some explanation as why this occurs and how to remedy it? And put in the documentation because there seem to be quite some people that have it.

Also, the `var options = BuildOptions.AcceptExternalModificationsToPlayer;` won't work any longer. I edited it to 
`var options = BuildOptions.AllowDebugging` which made it compile but I'm not a 100% sure that this is okay.

Unity version: 2020.2.1f1
