### ISSUE TITLE
:arcore_client Missing Package Error

### ISSUE THREAD

**Issue by hzlgnn** [juicycleff/flutter-unity-view-widget#233]
Hello,

I created unity- flutter integration with basic scene.  But when I try to create scene that include some packages (arcore_client, UnityARCore, ARPresto, unityandroidpermissions), I get an arcore_client Missing Package Error.

I created a folder for these packages and I added  build.gradle files for all packages. 

**../android/UnityArCore/build.gradle**
configurations.maybeCreate("default")
artifacts.add("default", file('unityandroidpermissions.aar'))

I changed the dependencies in UnityLibrary/build.gradle file.
**../android/unityLibrary/build.gradle**
dependencies {
    implementation project(':unity-classes')
    implementation project(':arcore_client')
    implementation project(':ARPresto')
    implementation project(':UnityARCore')
    implementation project(':unityandroidpermissions')
}

I added settings.gradle file these code:
**../android/settings.gradle**
include ':app',':unity-classes', ':arcore_client',':ARPresto',':UnityARCore',':unityandroidpermissions'

I changed minSDK to 24.
<img width="1439" alt="Ekran Resmi 2020-10-24 20 03 01" src="https://user-images.githubusercontent.com/16907704/97087605-fb49e800-1633-11eb-81e0-596c1759c449.png">

Could you help me please?
Thank you

**Comment by Darkmax** [comment]
I also presenting this error

**Comment by bedirhandev** [comment]
My approach for fixing this issue is as follows @hzlgnn. I tried this with the latest stable version of Flutter and with Unity 2019.4.12 and the latest version of ARFoundation and Universal RP 7.3.1 as this is the one recommended with the used version of Unity. 

The main problem is that Gradle is not up-to-date with the needs of ARCore inside of Flutter. You need to update Gradle.

You need to do this in the file **<flutter project>/android/build.gradle**, replace the gradle build tool path with the following: **classpath 'com.android.tools.build:gradle:3.6.2'**. Next step edit this file: **<flutter project>/android/gradle/wrapper/gradle-wrapper.properties** and replace the distribitionUrl with this: **distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip**. Finally, go to this destination in the terminal: **<flutter project>/android**. Then enter the command: **gradlew wrapper --gradle-version=6.2.1**. This should update everything in your Flutter project. Run the commands; **flutter clean**, **flutter build apk**, **flutter install -d <device-id>** and you should be good to go!

**Comment by huzaifaedhi22** [comment]
Did you find a solution to this?
