### ISSUE TITLE
Flutter UI disappearing and appearing in Unity arcore scene

### ISSUE THREAD

**Issue by GPavlioudakis** [juicycleff/flutter-unity-view-widget#265]
I have a button over unity widget in ar scene and when I press it every flutter widgets disappears or blips.
I get this message on console: 
W/ImageReader_JNI(15587): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers

**Comment by wanghuasheng** [comment]
我也遇到了，好像是flutter引擎的问题

**Comment by diybl** [comment]
> 我也遇到了，好像是flutter引擎的问题

解决了吗？？我也遇到。  稍微多一些 stack的ui就会出这种问题 还一闪一闪的。
感觉不太稳定。。

**Comment by cmd-dev** [comment]
I am getting the same exact issue, if I have 3 widgets on top then it works properly but If I add one more on top in the stack then every widget on top starts blinking @diybl @wanghuasheng

**Comment by vicmaurer** [comment]
Hi @cmd-dev were you able to solve the issue? I saw you were redirected to b5dd0d903ee538e237ab068622f92259311b9a7a on #308 saying that reverting back to **AndroidView** instead of **PlatformViewLink** would solve the issue. I have tried `useAndroidView=true` with the latest version of the package (**4.0.2**) yet the Unity view does not even seem to initiate. 

@juicycleff  
While multiple individual widgets are drawn over the  `UnityWidget()` in a `Stack()` the error and the blinking glitches happen for me the moment I either reopen the app after minimizing it (i.e. open native camera, switch to another app, etc...). 

![image](https://user-images.githubusercontent.com/31721157/113411709-1988f080-93e9-11eb-903e-3c6ff34aabaa.png)

When commenting out the majority of  the widgets in the stack the error does not occur and **PlatformViewLink** runs much smoother than AndroidView.  

A similar bug I have seen on another thread that may or may not be related https://github.com/flutter/engine/pull/24272

Phone : Huawei Mate 20 Pro
flutter 2.0.3 (but also tried with earlier versions)
unity 2019.4.3f1

**Comment by dawiddszewczyk** [comment]
Hi this issue is outdated can you upgrade the unity flutter version, flutter version, and reimport the unity project with the new [unity widget package](https://github.com/juicycleff/flutter-unity-view-widget/tree/master/unitypackages).
If this issue still works please reopen issue or create new :)
