### ISSUE TITLE
Embed Unity in Flutter Desktop

### ISSUE THREAD

**Issue by DaniloCCP** [juicycleff/flutter-unity-view-widget#307]
It is possible to embed a Unity Application within a Flutter Desktop one? How could the unity windows/macos build be added as a library?

**Comment by DirtyNative** [comment]
I also want to embed it into my Desktop app. Is this possible?

**Comment by igrir** [comment]
looks like this is possible by utilizing UWP
https://docs.unity3d.com/Manual/UnityasaLibrary-Windows.html

**Comment by jhancock4d** [comment]
@igrir FYI, Microsoft just officially killed UWP.  Project Reunion is the way to get this done now. But that will require either C++ code or Flutter .NET Bindings which don't exist.  Of course, The Desktop UI workload doesn't even really exist right now because Microsoft is a mess.

https://github.com/flutter/flutter/issues/64958
