### ISSUE TITLE
Can't send data from unity to flutter on iOS TestFlight and Ready on Sale

### ISSUE THREAD

**Issue by phamtuongvan** [juicycleff/flutter-unity-view-widget#327]
Archive app and up to appstore but can't receive data from unity, just send data from flutter to unity only. Anyone help me.

**Comment by mathtasatlime** [comment]
Can you please describe your bug a bit more precise? Is it also occurring with the lastest version 4.0.0-alpha4. Have you also used the lastet version of the FlutterUnityIntegration package in Unity? DId you try the example project to see if the problem isn't occurring due to other problems arising in your project, unrelated to the flutter_untiy_view_widget? Thanks!

**Comment by juicycleff** [comment]
No response, so I'm closing it. Reopen if you still have issues

**Comment by mathtasatlime** [comment]
I had the same problem. The fix is to add  -keep class com.xraph.plugin.** {*;} into the proguard of your unityLibrary.

@juicycleff You have to fix it in your readme, since there you write 'plugins' instead of 'plugin' !
