### ISSUE TITLE
AR project, Universal Render Pipeline renders blackscreen

### ISSUE THREAD

**Issue by danielbruttyo** [juicycleff/flutter-unity-view-widget#386]
I use AR Foundation and the Universal Render Pipeline package in Unity, and it works fine when building straight from Unity, but after exporting with the flutter plugin, it displays a blackscreen. The strange thing is that planes are still detected and displayed (so AR Foundation gets the camera information), but the camera's image is not rendered.

I suspect that the Universal RP package doesn't get exported with the other packages.

Has anybody faced this problem before?

**Comment by timbotimbo** [comment]
Did you follow [these instructions](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.1/manual/ar-camera-background-with-scriptable-render-pipeline.html) to add an `ARBackgroundRendererFeature`?
And if you already did, maybe try moving these files into a `Resources` folder instead of Rendering, to maybe force them to be included.

Haven't tried this yet, but I did run ARfoundation in URP before in flutter. I switched back because URP messed up on iOS, and don't remember what I did to set it all up.
