### ISSUE TITLE
[Stolen Code]: Licence referencing the plugin developers missing! -> Web

### ISSUE THREAD

**Issue by Ahmadre** [juicycleff/flutter-unity-view-widget#568]
@juicycleff 

If you copy my code and https://pub.dev/packages/flutter_unity_widget_web 's code, then you have to mention us in the Copyright of your plugin here!

It's a bad practice to steal code and not mention us in the licence like I did!

Open Source means giving and not taking!

**Comment by juicycleff** [comment]
Are you kidding me, seriously are you kidding me. I copied your unity web project. This is laughable. Please if you feel like I copied your project go one thinking that way. And to be frank it's the first time I'm seeing this, plus I don't have to prove anything to you. Take care @Ahmadre

**Comment by Ahmadre** [comment]
> Are you kidding me, seriously are you kidding me. I copied your unity web project. This is laughable. Please if you feel like I copied your project go on thinking that way. And to be frank it's the first time I'm seeing this, plus I don't have to prove anything to you. Take care @Ahmadre 

Nope: RefreshUnityView Is from me ;)

The web project was buggy from samuel ;)

**Comment by Ahmadre** [comment]
I can clearly see what comes from me or samuel.

**Comment by juicycleff** [comment]
And to add to this because you just pissed me off. Is there not a shared documentation for webgl unity what are you going on about. Miss me with this, if it gives you joy. More glory to you. But it's the last message you will get from me ✌️ @Ahmadre

**Comment by Ahmadre** [comment]
This is a copyright violation. I noticed your about that. If you don't name Samuel and Me in the Licence, I have to raise a violation on Github.

Thx

**Comment by juicycleff** [comment]
Yes please feel free, and I will raise the same. You know what I think I have your time @Ahmadre. I will raise it here and will raise it on pub dev. I'd had enough of people like you bugging me, usually, I just ignore but let's play your game.

**Comment by juicycleff** [comment]
Yes please feel free, and I will raise the same. You know what I think I have your time @Ahmadre. I will raise it here and will raise it on pub dev. I'd had enough of people like you bugging me, usually, I just ignore but let's play your game.

**Comment by juicycleff** [comment]
@Ahmadre you know you are full of shit, you copied this repo https://github.com/Glartek/flutter-unity and then came after me for stealing your code. You are laughable. bring on your DMCA. In fact, I will reopen this issue so everyone sees it and even pin it.

**Comment by juicycleff** [comment]
@Ahmadre you know you are full of shit, you copied this repo https://github.com/Glartek/flutter-unity and then came after me for stealing your code. You are laughable. bring on your DMCA. In fact, I will reopen this issue so everyone sees it and even pin it.

**Comment by juicycleff** [comment]
PINING SO WE SEE WHERE THIS CRAZINESS LEADS.

**Comment by juicycleff** [comment]
PINING SO WE SEE WHERE THIS CRAZINESS LEADS.

**Comment by Ahmadre** [comment]
I think you did not understand how Licence's work in Open-Source.

I mentioned every single developer of flutter_unity and flutter flutter_unity_widget_web ;)

This is how you respect others work if you improve something on the BSD-3 Clause ;)

**Comment by juicycleff** [comment]
And I know that but you coming to say I took from your code to implement web is just preposterous, so which part of the code did I steal from you, screenshot it and add it here. You have all the commit history.

**Comment by juicycleff** [comment]
And I know that but you coming to say I took from your code to implement web is just preposterous, so which part of the code did I steal from you, screenshot it and add it here. You have all the commit history.

**Comment by juicycleff** [comment]
I mean I worked on web support last night and it was left with some bug, I pushed to work on my windows machine since I'm working on windows support there, and my code pushed was failing as it wasn't complete, only for me to get your issue, and then saying I copied your web support, and I'm trying to hide it and removing the history, whats all this BS.

I'm here trying to fix support for the web with the little time I have over the weekend and only for you to come after me, I mean did you write the Unity as a Library Documentation, are the Autor of Unity Docs. Got do this with someone else and please screenshot all your code and DMCA it. And mind you I have other opensource projects, I reference projects in code and also add them in my readme, so go look for someone to bicker. 

You cloned my project and took the changes of another project and to be honest, I don't care, there are tons of people that clone my project and release it on pub dev. I don't care if it helps your project, great and I don't care. But don't drag me to your clout seeking, if you think adding support for web on my project is rocket science then you clearly do not kno who you are messgaing. And don't email me again, lese i will report your email. Keep your harasment here so all can see.

**Comment by juicycleff** [comment]
I mean I worked on web support last night and it was left with some bug, I pushed to work on my windows machine since I'm working on windows support there, and my code pushed was failing as it wasn't complete, only for me to get your issue, and then saying I copied your web support, and I'm trying to hide it and removing the history, whats all this BS.

I'm here trying to fix support for the web with the little time I have over the weekend and only for you to come after me, I mean did you write the Unity as a Library Documentation, are the Autor of Unity Docs. Got do this with someone else and please screenshot all your code and DMCA it. And mind you I have other opensource projects, I reference projects in code and also add them in my readme, so go look for someone to bicker. 

You cloned my project and took the changes of another project and to be honest, I don't care, there are tons of people that clone my project and release it on pub dev. I don't care if it helps your project, great and I don't care. But don't drag me to your clout seeking, if you think adding support for web on my project is rocket science then you clearly do not kno who you are messgaing. And don't email me again, lese i will report your email. Keep your harasment here so all can see.

**Comment by juicycleff** [comment]
Should I refernce this Stackoverflow for Pointers https://stackoverflow.com/questions/52114299/send-string-to-unitywebgl-jslib

**Comment by juicycleff** [comment]
Should I refernce this Stackoverflow for Pointers https://stackoverflow.com/questions/52114299/send-string-to-unitywebgl-jslib

**Comment by juicycleff** [comment]
Or wait should I reference unity docs https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html, oh wait Unity is mentioned everywhere. You should do better with your time. You insult but don't again come after my character

**Comment by juicycleff** [comment]
Or wait should I reference unity docs https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html, oh wait Unity is mentioned everywhere. You should do better with your time. You insult but don't again come after my character

**Comment by juicycleff** [comment]
> > Are you kidding me, seriously are you kidding me. I copied your unity web project. This is laughable. Please if you feel like I copied your project go on thinking that way. And to be frank it's the first time I'm seeing this, plus I don't have to prove anything to you. Take care @Ahmadre
> 
> Nope: RefreshUnityView Is from me ;)
> 
> The web project was buggy from samuel ;)



> > Are you kidding me, seriously are you kidding me. I copied your unity web project. This is laughable. Please if you feel like I copied your project go on thinking that way. And to be frank it's the first time I'm seeing this, plus I don't have to prove anything to you. Take care @Ahmadre
> 
> Nope: RefreshUnityView Is from me ;)
> 
> The web project was buggy from samuel ;)

laughing that's the code I stole a function, that's 3 lines 😆  are you kidding me, should I get the stack overflow messgae. Ahaha so you think me removing it was hiding, 😆  SMH, I only removed that function as after refactoring the project on web and IO, I saw no need for it. And so your clame is I copied a function thats 3lines, with frame id that's the same for every single person running flutter web, are you being serious, how old are you again? Modifying a dom with thesmae name. This is my last message. You wear me out.

**Comment by juicycleff** [comment]
> > Are you kidding me, seriously are you kidding me. I copied your unity web project. This is laughable. Please if you feel like I copied your project go on thinking that way. And to be frank it's the first time I'm seeing this, plus I don't have to prove anything to you. Take care @Ahmadre
> 
> Nope: RefreshUnityView Is from me ;)
> 
> The web project was buggy from samuel ;)



> > Are you kidding me, seriously are you kidding me. I copied your unity web project. This is laughable. Please if you feel like I copied your project go on thinking that way. And to be frank it's the first time I'm seeing this, plus I don't have to prove anything to you. Take care @Ahmadre
> 
> Nope: RefreshUnityView Is from me ;)
> 
> The web project was buggy from samuel ;)

laughing that's the code I stole a function, that's 3 lines 😆  are you kidding me, should I get the stack overflow messgae. Ahaha so you think me removing it was hiding, 😆  SMH, I only removed that function as after refactoring the project on web and IO, I saw no need for it. And so your clame is I copied a function thats 3lines, with frame id that's the same for every single person running flutter web, are you being serious, how old are you again? Modifying a dom with thesmae name. This is my last message. You wear me out.
