### ISSUE TITLE
Unable to Distribute or Validate the archive/app to AppleStore!

### ISSUE THREAD

**Issue by RoyalCoder88** [juicycleff/flutter-unity-view-widget#571]
Hi friends,

I'm new to the Apple Development environment, I'm developing an app in Flutter, my problem appears after adding flutter_unity_widget 2022.1.0+2, I'm building a mini-game that is integrated into my app with Unity framework, and I'm able to build and archive the app but not to Distribute or Validate it on store? 

What can cause this issue?
It's possible to be related to bundle identifiers, the Unity build should have the same bundle id as the flutter app?

Screenshots attached!

Thanks in advance!

![1](https://user-images.githubusercontent.com/6507433/166914423-52e49adf-e6e2-4923-b9db-27a29c22b7cc.jpg)
![2](https://user-images.githubusercontent.com/6507433/166914427-3952a58c-8532-4c77-b88e-6ba6f7760737.jpg)

**Comment by WellingtonBipo** [comment]
@RoyalCoder88  I faced the same issue. This other issue helped me.
https://github.com/juicycleff/flutter-unity-view-widget/issues/489#issuecomment-1002300077

**Comment by jamesncl** [comment]
@juicycleff I have also just encountered this problem - see duplicate issues #489 and #446 also. In `UpdateBuildSettings` of `XCodePostBuild.cs` there is this line:

```
// Set skip_install to NO 
pbx.SetBuildProperty(targetGuid, "SKIP_INSTALL", "NO");
```

This causes the issue of not being able to archive the project for distribution to App Store - instead of getting the "Distribute app" button you get "Distribute content":

![Screenshot 2022-06-01 at 10 46 57](https://user-images.githubusercontent.com/15979056/171376841-aa9c4372-046f-43b9-9edd-221d0b34c209.png)

According to @jpsarda setting this to "YES" in `XCodePostBuild.cs` resolves the issue, and doesn't seem to cause a problem. Can you remember why this is set to NO? If not, maybe this can be changed to YES so that it doesn't have to be manually set each time in Xcode?

**Comment by juicycleff** [comment]
@jamesncl yes it is set to NO for bundling unity project outside the  flutter, it will be useful for the  tool I'm open sourcing soon but for now will update it to YES

**Comment by juicycleff** [comment]
The unity package has been updated accordingly

**Comment by Ahmadre** [comment]
I will close this for now. @RoyalCoder88 if you need any further help with this issue, consider opening a new issue :3 thx.
