### ISSUE TITLE
Invalid Signature, code object is not signed at all. iOS

### ISSUE THREAD

**Issue by abdo400** [juicycleff/flutter-unity-view-widget#613]
**Expected behavior**
A complete upload like older versions

**Unity (please complete the following information):**
- Unity: 2020.3.30f1
- Unity flutter package (Unity side): 2022.1.1
- Flutter Unity package (Flutter side): flutter_unity_widget: ^2022.1.1+3
- Flutter version: 3.0.1

After building and trying to upload to the app store, I get this message:

```Invalid Signature. Code object is not signed at all. The file at path [Runner.app/Frameworks/
UnityFramework.tramework/Data/Raw/dnn/download_dnn_models.pylisnotproperlysigned
Make sure vou have sIoned vour a dstrun certte. nt an
certiticate or a develooment certiticate. Veriv inar the code sionina selinos in xcode are
correct at the target level (which override anv values at the proiect level). Additionallv. make
sure the bundle vou are uoloading was built using a Release target in Xcode. not a Simulatoi
laree.r vol gie cenain vour
code sianina settinas are correct. choose "Clean Al' in Xcode
delete the "build" director in the Finder. and rebuild vour release target. For more information
please consult httos://developer.apple.com/librarv/ios/documentation/Securitv/Conceptuall
CodeSigningGuide/Introduction/Introduction.htmlWith error code
STATE ERROR.VALIDATION ERROR.90035 for id 90072aed-e033-4011-
ae36-56e9a195€/68 ```

**Comment by jamesncl** [comment]
What is `download_dnn_models.py`? I don't recognise that, wondering if that's what the problem is.

In Xcode, go to Runner, select TARGETS : Runner, and in the General tab, scroll down to 'Frameworks, Libraries, and Embedded Content'. There should be an entry for UnityFramework.framework, and it should be set to `Embed & Sign`. Do you have that?

Also, could you repost your error message - the one above is malformed and it's difficult to read the text.

**Comment by abdo400** [comment]
<img width="738" alt="Screen Shot 2022-06-15 at 10 45 13 AM" src="https://user-images.githubusercontent.com/17462579/173784475-edc2e521-4039-469f-92ef-0f4f99c8443f.png">

**Comment by abdo400** [comment]
Yes, I have the Unityframework.framework in the 'Targets -> Runner -> General -> Framework, Libraries, and Embedded Content'
I also have automatic signing enabled for the unity project, and the Signing Team ID, the bundle identifier is 'com.unity3d.framework' as xCode sees it.

**Comment by codechef703** [comment]
Hi, this is Seno.K from Upwork. unfortunately my account has been suspended and can't contact you on there.

**Comment by jamesncl** [comment]
Can you make sure you don't have 'development build' ticked in the main build settings menu

Also, you don't need to enable automatic signing in the Unity player settings. In Player settings -> Other settings, if you have 'automatically sign' ticked, try unticking it. That setting is for when you are just using Unity to build and publish a game straight to the App Store. For this package, it's actually Xcode (not Unity) that is doing the signing (because it needs to sign flutter and unity at the same time). Then run through the whole export / build process again (you might also want to clean the build folder in xcode).

**Comment by abdo400** [comment]
I don't have "development build" checked in build settings, and "automatically sign" is not also checked in the Unity project.
One thing worth mentioning is that UnityFramework and Unity-iPhone (in Unity-iPhone -> Targets) don't have the same Bundle identifier as the app

**Comment by abdo400** [comment]
I just tried it that way, after cleaning the build and exporting again. 
It still didn't work though. 
Does the bundle identifier for "Unity-iPhone & UnityFramework" plays any role in this?

**Comment by dawiddszewczyk** [comment]
@abdo400  No, there you don't have to change bundle of Unity-Phone & Unity Framework. Check if you have like there:
(Runner -> Targets Runner -> Framework,Libraries)
<img width="550" alt="Zrzut ekranu 2022-07-17 o 00 14 07" src="https://user-images.githubusercontent.com/58904662/179373461-00d64d07-95f3-4026-851d-68d6aca6fcde.png">

**Comment by abdo400** [comment]
I had to delete the mentioned file to let Apple accept it, which is download_dnn_models.py .
