### ISSUE TITLE
Demo App doesn't work on windows

### ISSUE THREAD

**Issue by anilozfuttu** [juicycleff/flutter-unity-view-widget#690]
I build demo app project on windows unity 2022.1.16f1 and it generated library files under windows folder.

But when I build and run the project for windows scene is empty with following errors;

When the exception was thrown, this was the stack:
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      _SimpleScreenState.setRotationSpeed (package:flutter_unity_widget_example/screens/simple_screen.dart:87:28)
#2      _SimpleScreenState.build.<anonymous closure> (package:flutter_unity_widget_example/screens/simple_screen.dart:70:29)
#3      _SliderState._handleChanged (package:flutter/src/material/slider.dart:557:24)
#4      _RenderSlider._startInteraction (package:flutter/src/material/slider.dart:1312:17)
#5      _RenderSlider._handleDragStart (package:flutter/src/material/slider.dart:1346:5)
#6      DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:463:53)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#8      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:463:7)
#9      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:382:7)
#10     _CombiningGestureArenaMember.acceptGesture (package:flutter/src/gestures/team.dart:45:14)
#11     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:264:25)
#12     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:244:31)
(elided 2 frames from dart:async)

Handler: "onStart"
Recognizer:
  HorizontalDragGestureRecognizer#93ec3
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: NoSuchMethodError: The method 'postMessage' was called on null.
```
[Updated log formatting to not reference other issues]

**Comment by hu1won** [comment]
It looks like you are encountering an error in the__' setRotationSpeed'__ method of the __'_SimpleScreenState'__ class in the __'simple_screen.dart'__ file. This error is being caused by a NoSuchMethodError, which means that the method __'noSuchMethod'__ was called on an object that doesn't have this method defined.

The __'noSuchMethod'__ method is a special method in the __'Object'__ class that is called when an attempt is made to call a non-existent method on an object. It is generally used as a fallback when a method can't be found in the object's class or any of its superclasses.

To fix this error, you will need to identify the cause of the __'noSuchMethod'__ call and make sure that the object you are calling the method on has the appropriate method defined. This may involve modifying your code to correctly call a valid method, or it may involve adding the necessary method to the object's class.

**Comment by Daumas-hugo** [comment]
I have the same problem, it looks more like the fact that the unity Controller doesn't seem to instantiate, it's null every time we call it in the flutter part

**Comment by Daumas-hugo** [comment]
Is the Windows demo already available ? I saw that it was nearly done in the README.md of master and there is a branch, but there is still a Windows part in the example of master

**Comment by hu1won** [comment]
It sounds like an attempt to invoke a method on an object that is null, which results in an error 'noSuchMethod'. To resolve this issue, you must ensure that the object is instantiated before invoking a method for the object.

Regarding the availability of Windows demos, Windows demos do not appear to be available yet in the master branch of the repository, but they are currently in development and may be available in the future. You can learn more about the development status of Windows Demos by checking the branch office in the storage or the README.md file.

Share information from somewhere.

**Comment by timbotimbo** [comment]
Windows is not (yet) supported.
I will try to get the "windows soon" message removed from the readme.

It was a work in progress, but I don't think anyone is currently working on it.
The last commit in the windows branch is from October 2021.
