### ISSUE TITLE
The type or namespace name 'Newtonsoft', 'JObject', & 'JToken' could not be found

### ISSUE THREAD

**Issue by eenlpe1** [juicycleff/flutter-unity-view-widget#790]
**Describe the Bug:**
While I'm trying to follow how to set up flutter-unity in my unity enviroment, I encountered an error when I imported this file 
`fuw-2022.1.1.unitypackage` from the `flutter-unity-view-widget` Readme.

**Expected Behavior:**
It should compile without an error after importing the `fuw-2022.1.1.unitypackage`.

**Screenshot:**
![image](https://user-images.githubusercontent.com/109678010/225325190-e5c931a4-0976-48b6-aec9-9818f5d41d7f.png)

**Unity**
 - OS: [Windows 11]
 - Version: [Unity2021.3.20f1]

**Comment by timbotimbo** [comment]
Rename the `dll.txt` file extension in `/jsonDotNet/AOT` to `.ddl`
`Assets/FlutterUnityIntegration/JsonDotNet/Assemblies/AOT/Newtonsoft.Json.dll.txt`

The documentation needs to be updated regarding this.

This file used to be loaded in Unity 2019 and 2020, but since Unity 2021 this threw duplicate import errors since it was already included in Unity by default.

Some 2022 versions seem to have changed this again.
Simply including the dll file should make it work again.

**Comment by megaDRONe86** [comment]
You need to install UnityPackage through Unity PpackageManager: https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Install-official-via-UPM

**Comment by Krazy-kungfu** [comment]
you can install Newtonsoft json using package manager
1 - Open package manager 
2 - top left click the + icon 
3 - Add package by name 
4 - write com.unity.nuget.newtonsoft-json as package name and 3.0.1 as version number (the version number may be different in later updates)
this will essentially install the dependencies required in your project
