### ISSUE TITLE
 Library not loaded: @rpath/UnityFramework.framework/UnityFramework this error show after build successfully

### ISSUE THREAD

**Issue by akhileshv25** [juicycleff/flutter-unity-view-widget#974]
![Uploading Screenshot 2024-08-09 at 8.29.23 AM.png…]()
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Unity (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by timbotimbo** [comment]
Because this issue has zero new information and a broken screenshot, I'm closing this as a duplicate of https://github.com/juicycleff/flutter-unity-view-widget/issues/439.
[You already commented in](https://github.com/juicycleff/flutter-unity-view-widget/issues/439#issuecomment-2277052568) that issue with a working screenshot anyway.

I know it sucks running into an old issue that never got a satisfying response.
But I'm not aware of anyone being able to reproduce this, so I don't know how I could help either. 
Maybe you didn't follow the setup instructions properly.
